feat: 添加泰国的行政区划数据
TranscodeGroup/tg_flutter_plugins pull request #1
Opened 2023-02-15 09:34 UTC by limingnie

添加了泰国的行政区划数据

2023-02-15 10:13 UTC, jss-tg requested changes
其他修改点:
1. 更新外面的README
2. 将原始数据, 处理脚本, 等代码全部放进来版本管理

2023-02-15 10:13 UTC, jss-tg commented on packages/thailand_city_data/lib/src/province.dart
> +const Map<String, String> thaProvincesData = {
tha -> th

2023-02-15 10:13 UTC, jss-tg commented on packages/thailand_city_data/lib/src/district.dart
> +  'TH10': <String, Map<String, String>>{
只要在顶部标注类型就行了

2023-02-15 10:13 UTC, jss-tg commented on packages/thailand_city_data/pubspec.yaml
> +  flutter:
用dart创建一个纯dart包

2023-02-16 02:26 UTC, jss-tg requested changes

2023-02-16 02:26 UTC, jss-tg commented on packages/thailand_city_data/pubspec.yaml
> +homepage: https://github.com/TranscodeGroup/tg_flutter_plugins.git
写到package目录下面来

2023-02-16 02:32 UTC, jss-tg commented on packages/thailand_city_data/pubspec.yaml
> +homepage: https://github.com/TranscodeGroup/tg_flutter_plugins.git
```suggestion
homepage: https://github.com/TranscodeGroup/tg_flutter_plugins/tree/main/packages/thailand_city_data
```

2023-02-16 02:38 UTC, jss-tg requested changes

2023-02-16 02:38 UTC, jss-tg commented on packages/thailand_city_data/example/thailand_city_data_example.dart
> +void main() {}
将原始数据, 处理脚本, 等代码全部放进来版本管理

2023-02-16 02:40 UTC, jss-tg requested changes

2023-02-16 02:40 UTC, jss-tg commented on packages/thailand_city_data/README.md
> +Administrative division about Thailand.
添加数据来源的描述信息

2023-02-17 05:44 UTC, jss-tg requested changes

2023-02-17 05:44 UTC, jss-tg commented on .vscode/launch.json
> +{
.vscode不要传上来

2023-02-17 05:44 UTC, jss-tg commented on packages/huawei_share/example/pubspec.lock
> -      url: "https://pub.dartlang.org"
不要用国内的镜像
这个huwei_share项目的文件,别改它
revert掉它

2023-02-17 05:44 UTC, jss-tg commented on packages/thailand_city_data/example/thailand_city_data_example.dart
> +
如果是使用String默认的compareTo, 不需要额外传比较方法
```suggestion
final map = SplayTreeMap<String, Map<String, Map<String, String>>>();
```

2023-02-17 05:44 UTC, jss-tg commented on packages/thailand_city_data/example/thailand_city_data_example.dart
> +
其他两个地方也一样

2023-02-17 05:44 UTC, jss-tg commented on packages/thailand_city_data/example/thailand_city_data_example.dart
> +      '''/// Generate by xxx, DO NOT EDIT IT
完善提示不要编辑的信息
```suggestion
      '''/// Generated file. Do not edit.
```

2023-02-17 05:44 UTC, jss-tg commented on packages/thailand_city_data/example/thailand_city_data_example.dart
> +  final file = './example/excel/tha_adm_feature_areas_20191106.xlsx';
相对路径没必要用`.`开头
```suggestion
  final file = 'example/excel/tha_adm_feature_areas_20191106.xlsx';
```

2023-02-17 05:44 UTC, jss-tg commented on packages/thailand_city_data/example/thailand_city_data_example.dart
> +
迭代值, 不是只要这么写就行了吗?
```suggestion
  for (final table in excel.tables.values) {
```

2023-02-17 05:44 UTC, jss-tg commented on packages/thailand_city_data/example/thailand_city_data_example.dart
> +    path: './example/excel/tha_adm_feature_areas_output.xlsx',
输出文件不要添加到git里来

2023-02-17 05:44 UTC, jss-tg commented on packages/thailand_city_data/example/thailand_city_data_example.dart
> +  final newProvinceList = provinceList.map((province) {
解决掉新的lint规则下的警告

2023-02-17 05:48 UTC, jss-tg commented on packages/thailand_city_data/example/thailand_city_data_example.dart
> +        map.addEntries(mapEntry.entries);
往Map里添加值只要这样写就行了:
```dart
map[key] = value;
```

好几个地方, 都改下

2023-02-17 05:49 UTC, jss-tg commented on packages/thailand_city_data/example/thailand_city_data_example.dart
> +        final key = data0Value.toString();
读个key怎么写了三行? 写成一行不行吗?

2023-02-17 05:50 UTC, jss-tg commented on packages/thailand_city_data/example/thailand_city_data_example.dart
> +  // 1.
`1.` 啥? 这个注释没写完?

2023-02-17 05:50 UTC, jss-tg commented on packages/thailand_city_data/example/thailand_city_data_example.dart
> +    ..writeAsBytesSync(fileBytes!);
更推荐统一用await版的方法

2023-02-17 07:11 UTC, limingnie commented on packages/thailand_city_data/example/thailand_city_data_example.dart
> +    path: './example/excel/tha_adm_feature_areas_output.xlsx',
已删除

2023-02-17 07:12 UTC, limingnie commented on packages/thailand_city_data/example/thailand_city_data_example.dart
> +      '''/// Generate by xxx, DO NOT EDIT IT
已完善

2023-02-17 07:15 UTC, limingnie commented on packages/thailand_city_data/example/thailand_city_data_example.dart
> +
已解决

2023-02-17 07:16 UTC, limingnie commented on packages/thailand_city_data/example/thailand_city_data_example.dart
> +
已修改

2023-02-17 07:20 UTC, limingnie commented on packages/thailand_city_data/example/thailand_city_data_example.dart
> +        final key = data0Value.toString();
已改

2023-02-17 07:21 UTC, limingnie commented on packages/thailand_city_data/example/thailand_city_data_example.dart
> +        map.addEntries(mapEntry.entries);
已改

2023-02-17 09:21 UTC, jss-tg approved these changes

2023-02-17 09:21 UTC, merged